### ISSUE TITLE
Fulcio panics when trying to index out of bounds

### ISSUE THREAD

**Issue by vaikas** [sigstore/fulcio#394]
**Description**

When doing some testing with Spiffe integration that went swimmingly, found this along the way:

```
2022/02/08 02:12:57 http: panic serving 127.0.0.1:38618: runtime error: index out of range [2004] with length 1436
goroutine 132 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1802 +0xb9
panic({0xc4f760, 0xc0000ae2a0})
	runtime/panic.go:1047 +0x266
github.com/sigstore/fulcio/pkg/api.(*api).signingCert(0xc000636500, {0x7f214a54eeb8, 0xc00062a190}, 0xc000224700)
	github.com/sigstore/fulcio/pkg/api/ca.go:218 +0x1109
net/http.HandlerFunc.ServeHTTP(0x7f214a5c9510, {0x7f214a54eeb8, 0xc00062a190}, 0x7f21714fdf18)
	net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x40d2c7, {0x7f214a54eeb8, 0xc00062a190}, 0xc000224700)
	net/http/server.go:2425 +0x149
github.com/sigstore/fulcio/cmd/app.runServeCmd.func2.1({0x7f214a54eeb8, 0xc00062a190}, 0xc000224600)
	github.com/sigstore/fulcio/cmd/app/serve.go:194 +0x271
net/http.HandlerFunc.ServeHTTP(0xdc3d50, {0x7f214a54eeb8, 0xc00062a190}, 0x0)
	net/http/server.go:2047 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1({0xdc3d50, 0xc00062c000}, 0xc000224600)
	github.com/prometheus/client_golang@v1.12.0/prometheus/promhttp/instrument_server.go:76 +0xf5
net/http.HandlerFunc.ServeHTTP(0x0, {0xdc3d50, 0xc00062c000}, 0x1)
	net/http/server.go:2047 +0x2f
github.com/sigstore/fulcio/pkg/api.WithMaxBytes.func1({0xdc3d50, 0xc00062c000}, 0xc000224600)
	github.com/sigstore/fulcio/pkg/api/max_bytes.go:25 +0x11b
net/http.HandlerFunc.ServeHTTP(0x0, {0xdc3d50, 0xc00062c000}, 0x693c00)
	net/http/server.go:2047 +0x2f
net/http.serverHandler.ServeHTTP({0xdc1c08}, {0xdc3d50, 0xc00062c000}, 0xc000224600)
	net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0006221e0, {0xdc7858, 0xc0003dea50})
	net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	net/http/server.go:3034 +0x4e8
```

**Comment by vaikas** [comment]
This is a dupe of #369
