### ISSUE TITLE
`GetIssuer` just panics rather than issuing a useful error when there's no networking

### ISSUE THREAD

**Issue by 06kellyjac** [sigstore/fulcio#480]
**Description**

`GetIssuer` panics when there's no network access

https://github.com/sigstore/fulcio/blob/v0.2.0/pkg/config/config_test.go#L104

```
PASS
ok      github.com/sigstore/fulcio/pkg/challenges       0.270s
=== RUN   TestMetaURLs
=== RUN   TestMetaURLs/AWS_meta_URL
=== RUN   TestMetaURLs/GKE_meta_URL
--- PASS: TestMetaURLs (0.00s)
    --- PASS: TestMetaURLs/AWS_meta_URL (0.00s)
    --- PASS: TestMetaURLs/GKE_meta_URL (0.00s)
=== RUN   TestLoad
--- FAIL: TestLoad (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x753673]

goroutine 9 [running]:
testing.tRunner.func1.2({0x79cc00, 0xada640})
        testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        testing/testing.go:1212 +0x218
panic({0x79cc00, 0xada640})
        runtime/panic.go:1038 +0x215
github.com/sigstore/fulcio/pkg/config.(*FulcioConfig).GetIssuer(0x0, {0x7fea68, 0x1b})
        github.com/sigstore/fulcio/pkg/config/config.go:85 +0x93
github.com/sigstore/fulcio/pkg/config.TestLoad(0xc0000b9860)
        github.com/sigstore/fulcio/pkg/config/config_test.go:104 +0x165
testing.tRunner(0xc0000b9860, 0x814b28)
        testing/testing.go:1259 +0x102
created by testing.(*T).Run
        testing/testing.go:1306 +0x35a
FAIL    github.com/sigstore/fulcio/pkg/config   0.006s
```

**To reproduce**

1. have the repo
2. run `go mod vendor` so we have the dependencies available
3. `docker run -v $PWD:/fulcio --network=none -it golang`
4. `cd /fulcio` and `go test ./... -v`

**Remediation**

There should probably be an error that's more useful than a panic

Also it'd be nice for all tests that require networking to be tagged so we can avoid them within our hermetic nix build environment that doesn't have network access :slightly_smiling_face:

**Comment by nsmith5** [comment]
Oh dang that is lame. Thanks for the bug report! I think this test is triggering OIDC discover and making a network call because of it
