### ISSUE TITLE
Getting panic during initialization hashivault

### ISSUE THREAD

**Issue by Dentrax** [sigstore/fulcio#654]
**Description**

I followed the [Build Your Own Certificate Authority (CA)](https://learn.hashicorp.com/tutorials/vault/pki-engine) article from the beginning to get my PEM-encoded cert chain. Then configured my flags as described at [KMS](https://github.com/sigstore/fulcio/blob/main/docs/setup.md#kms=) section. The panic line is [sigstore/sigstore/pkg/signature/kms/hashivault/client.go#L202](https://github.com/sigstore/sigstore/blob/f8773a20132dbb2912d450bbeaff172022f6f473/pkg/signature/kms/hashivault/client.go#L202)

```
$ go run . serve --port 5555 --ca kmsca --kms-resource=hashivault://pki_int --kms-cert-chain-path=intermediate.cert.pem
```

Panic:

```
panic: runtime error: invalid memory address or nil pointer dereference

runtime/debug.Stack()
        /usr/local/Cellar/go/1.18.3/libexec/src/runtime/debug/stack.go:24 +0x65
golang.org/x/sync/singleflight.newPanicError({0x4c820a0?, 0x5909760})
        /Users/furkan.turkal/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/singleflight/singleflight.go:35 +0x2c
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
        /Users/furkan.turkal/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/singleflight/singleflight.go:188 +0x3b
panic({0x4c820a0, 0x5909760})
        /usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:838 +0x207
github.com/sigstore/sigstore/pkg/signature/kms/hashivault.(*hashivaultClient).fetchPublicKey(0xc000591640, {0x0?, 0xc000660da8?})
        /Users/furkan.turkal/go/pkg/mod/github.com/sigstore/sigstore@v1.2.1-0.20220526001230-8dc4fa90a468/pkg/signature/kms/hashivault/client.go:202 +0x146
github.com/sigstore/sigstore/pkg/signature/kms/hashivault.(*hashivaultClient).keyCacheLoaderFunction(0x0?, {0xc000130660?, 0xc000658180?})
        /Users/furkan.turkal/go/pkg/mod/github.com/sigstore/sigstore@v1.2.1-0.20220526001230-8dc4fa90a468/pkg/signature/kms/hashivault/client.go:185 +0x27
github.com/ReneKroon/ttlcache/v2.(*Cache).invokeLoader(0xc000180c00?, {0x4e0a468, 0x6}, 0x0?)
        /Users/furkan.turkal/go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:404 +0x35
github.com/ReneKroon/ttlcache/v2.(*Cache).GetByLoaderWithTtl.func1()
        /Users/furkan.turkal/go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:370 +0x2d
golang.org/x/sync/singleflight.(*Group).doCall.func2(0xc00080ff56, 0xc00053e660, 0xc00039a060?)
        /Users/furkan.turkal/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/singleflight/singleflight.go:193 +0x6f
golang.org/x/sync/singleflight.(*Group).doCall(0xc000658300?, 0xc000660fd0?, {0x4e0a468?, 0x27?}, 0x0?)
        /Users/furkan.turkal/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/singleflight/singleflight.go:195 +0xa5
created by golang.org/x/sync/singleflight.(*Group).DoChan
        /Users/furkan.turkal/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/singleflight/singleflight.go:133 +0x2eb


goroutine 80 [running]:
golang.org/x/sync/singleflight.(*Group).doCall.func1.2()
        /Users/furkan.turkal/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/singleflight/singleflight.go:162 +0x2a
created by golang.org/x/sync/singleflight.(*Group).doCall.func1
        /Users/furkan.turkal/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/singleflight/singleflight.go:162 +0x27b
exit status 2
```

My `pem` file (Specially created for this demo, no need to redaction):

```
-----BEGIN CERTIFICATE-----
MIIDpjCCAo6gAwIBAgIUDqNL7H6KRqmkse0zbAAIVVy3kNowDQYJKoZIhvcNAQEL
BQAwFjEUMBIGA1UEAxMLZXhhbXBsZS5jb20wHhcNMjIwNjIwMDkyNDE1WhcNMjcw
NjE5MDkyNDQ1WjAtMSswKQYDVQQDEyJleGFtcGxlLmNvbSBJbnRlcm1lZGlhdGUg
QXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsBWDNpk8
yqxmRKOeFzc4iy88JkEpz+8zw3p01QCEK7wdUvAacVLHfFQz4+oqRSRLuxUlHuxF
CyVHEMMC+WsouOkcqCBy2zOcI0DOgRMD3kPKZxZkGFTIiOAAvvRKBq7zG/IftHQU
uu16Uvj0vdGZNk0IqLvJkhZPK6rLYfBTgkjG0p+rGSMyObr3Kymi9qHLrK8pUAxk
/6+dj+uK8PtK1Gm4B5sH8TFNihfLx+xblOjlYYjukjN6xnhxGb7N8eAhEdGjGwwd
am2sZV/LhznOsIlzSaMHKTmeDfnigV6xrosOSziAKQlYkYwrcQbG8Yr8Tr3WnR45
xA+RUWAPNzrEwQIDAQABo4HUMIHRMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8E
BTADAQH/MB0GA1UdDgQWBBSyKjX77axAdY7dvNYHg2Cz9zmD7zAfBgNVHSMEGDAW
gBSAdyR3fO3hJNfwrx6UgmXPGriNbjA7BggrBgEFBQcBAQQvMC0wKwYIKwYBBQUH
MAKGH2h0dHA6Ly8xMjcuMC4wLjE6ODIwMC92MS9wa2kvY2EwMQYDVR0fBCowKDAm
oCSgIoYgaHR0cDovLzEyNy4wLjAuMTo4MjAwL3YxL3BraS9jcmwwDQYJKoZIhvcN
AQELBQADggEBABFK5ku84pI+75sfvnieOu/bpZVdmnJj5fkR0V0Y+NOQVlVG9saV
46fc3HC9YRJlT9Rnnh8F7E7cUS94NdDetoRGOv5sSufAyHVHpSOZc2w1tXbxGvBl
py7JDGH9Hrw8PjFp1jNBgQDcT9nDBe6XRuXBj7srm+s2z3GJMuxzIb3mRtesFVhF
64g5VmfrCCity7YM9LSuPks0x2CbhjU6uzcTLngPZELnlakISKzX8Psn1m4BpdGH
mK8dLpmfL3HhnszrmDORc8h4gOnKwViOD70Yk8xba/fQCN2SCaZE3gTyiRsNxBjd
6pl5YLLn7TGiEfRUY5hoigQFU5ofyK3JTAY=
-----END CERTIFICATE-----
```

**Version**

d54330c45f9c271fdf5b9d7eebe08284a700387f

What exactly I'm missing here? 🤔

**Comment by haydentherapper** [comment]
@Dentrax, do you want to update Fulcio's sigstore version to pick up this fix?

**Comment by Dentrax** [comment]
Yes, will do! I was waiting for the following PR to be merged before do bump the sigstore version:

https://github.com/sigstore/sigstore/pull/522
